<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMOIsve2\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMOIsve2/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMOIsve2.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMOIsve2\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerMOIsve2\App_KernelDevDebugContainer([
    'container.build_hash' => 'MOIsve2',
    'container.build_id' => 'ade0cd7a',
    'container.build_time' => 1704811150,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMOIsve2');
